dev: prevent dev from being run as root or with sudo
fixes https://github.com/cockroachdb/cockroach/issues/84732

Release note: None

diff --git a/dev b/dev
--- a/dev
+++ b/dev
@@ -1,5 +1,10 @@
 #!/usr/bin/env bash
 
+if [[ $EUID -eq 0 ]]; then
+  echo "dev cannot be run as root or with sudo"
+  exit 1
+fi
+
 set -euo pipefail
 
 # Bump this counter to force rebuilding `dev` on all machines.
