roachprod: pre-bake custom roachprod cloud images
Prior to this patch, roachprod clusters were created from bare Ubuntu
images.

This was inadequate for multiple reasons, some of which being:
- dependency on third-parties (GCS, APT repositories) availability
- spinning up two clusters at a different moment in time could lead to
  different resulting systems (package versions, ...) and create
reproducibility issues
- growing number of dependencies installed increases the boot time

To address this, this patch creates a new roachprod bake-images command
that relies on Hashicorp Packer to pre-bake ready to use cloud images
for AWS and GCP. This creates a system dependency on Packer and requires
the machine that runs the command to have Packer installed and to be
authenticated on AWS and GCP with authorization to create instances and
publish new images. If an image already exist, it won't get built again,
making re-running roachprod bake-images safe.

The pre-baking process creates images for amd64, arm64 and fips, and
pushes them to the roachprod compatible regions (only for AWS, since
images are globally available in GCP). The images are tagged with a
hashed checksum of the startup script, which defines their unique
version.

At runtime, the providers checksums the startup script to figure out
which pre-baked image should be used, and checks for its availability in
the cloud provider for that specific region/zone:
- if the image exists, it is used to create the instance, and only a
  subset (runtime) of the startup scripts is executed on the instances,
  decreasing the startup time to a minimum (5s or so for disk setup)
- if the image does not exists, the system fallbacks to using the base
  image and the whole startup scripts (pre-baking + runtime) is executed
  on the instances

This patch also drops the JSON hardcoded AMI IDs (or names in GCP) and
introduces auto-discovery of the base image's most recent version based
on the image name/family and owner or project ID. This allows us to
automatically keep up to date with the latest patch releases, which
usually are security updates.

Notes:
- this patch only contains implementation for AWS and GCP, and Azure and
  IBM should also be implemented
- a CI mechanism should be built to automatically build all images when
  there is a change in the startup scripts (either Github upon merge to
master or TeamCity nightly runs)
- there is currently no built-in way to deprecate/cleanup previous
  images since they might still be used on older branches; a cleanup
  routine should be considered if/when the number of images get out of
  hand

Beyond this first iteration, a concept of "pre-bake only snippets"
should come next: snippets that are only executed at pre-baking time and
not at runtime even if there is no pre-baked image.
These snippets would contain adhoc roachtest setups
(building/pre-installing third party tools like Prometheus/Grafana,
Jepsen, Kafka CLI, ...), which would remove the need for these tests to
build/install at third party dependencies at runtime if the test is
running on an instance supported by a pre-baked image (see #62066 as an
example).

Epic: none
Informs: #150144
Release note: None

diff --git a/pkg/roachprod/vm/gce/testdata/startup_script b/pkg/roachprod/vm/gce/testdata/startup_script
--- a/pkg/roachprod/vm/gce/testdata/startup_script
+++ b/pkg/roachprod/vm/gce/testdata/startup_script
@@ -7,6 +7,8 @@ echo
 function setup_disks() {
 	first_setup=$1
 
+	echo "startup script disk setup starting: $(date -u)"
+
 
 
 
@@ -99,6 +101,8 @@ function setup_disks() {
 	chmod a+w /mnt/data1/cores
 
 	sudo touch /mnt/data1/.roachprod-initialized
+
+	echo "startup script disk setup ending: $(date -u)"
 }
 
 
@@ -117,19 +121,49 @@ if [ -e /mnt/data1/.roachprod-initialized ]; then
 	exit 0
 fi
 
-# Uninstall some packages to prevent them running cronjobs and similar jobs in
-# parallel Check if the service exists before trying to stop it, because it may
-# have been removed during a previous invocation of this script.
-if systemctl list-unit-files | grep -q '^unattended-upgrades.service'; then
-    echo "unattended-upgrades service exists. Proceeding with uninstallation."
-    systemctl stop unattended-upgrades
-    sudo rm -rf /var/log/unattended-upgrades
-    apt-get purge -y unattended-upgrades
+
+# ensure any failure fails the entire script
+set -eux
+
+# Redirect output to stdout/err and a log file
+exec &> >(tee -a /var/log/roachprod_startup.log)
+
+# Log the startup of the script with a timestamp
+echo "startup script starting: $(date -u)"
+
+if [ -e /mnt/data1/.roachprod-initialized ]; then
+	echo "Already initialized, exiting."
+	exit 0
 fi
 
 
 
+# If enabled, disable unattended-upgrades to prevent it from interfering with
+# apt operations performed by the startup script.
+if systemctl list-unit-files | grep -q '^unattended-upgrades.service'; then
+
+    echo "unattended-upgrades service exists, disabling it and waiting for apt locks to clear."
+    systemctl stop unattended-upgrades
+
+	for i in {1..60}; do
+		if ! sudo fuser /var/lib/dpkg/lock-frontend /var/lib/apt/lists/lock >/dev/null 2>&1; then
+			break
+		fi
+		echo "Attempt $i/60: apt lock is held, waiting..."
+		sleep 1
+	done
+
+	# Clean up unattended-upgrades logs
+    sudo rm -rf /var/log/unattended-upgrades
+fi
+
+# Update package lists
 sudo apt-get update -q
+
+# Uninstall unattended-upgrades if it's installed.
+sudo apt-get remove -yq unattended-upgrades
+
+# Install required packages.
 sudo apt-get install -qy --no-install-recommends mdadm
 
 
@@ -151,7 +185,9 @@ setup_disks true
 # increase the default maximum number of open file descriptors for
 # root and non-root users. Load generators running a lot of concurrent
 # workers bump into this often.
-sudo sh -c 'echo "root - nofile 1048576\n* - nofile 1048576" > /etc/security/limits.d/10-roachprod-nofiles.conf'
+if [ ! -e /etc/security/limits.d/10-roachprod-nofiles.conf ]; then
+	sudo sh -c 'echo "root - nofile 1048576\n* - nofile 1048576" > /etc/security/limits.d/10-roachprod-nofiles.conf'
+fi
 
 
 
@@ -160,7 +196,9 @@ sudo sh -c 'echo "root - nofile 1048576\n* - nofile 1048576" > /etc/security/lim
 # See https://ubuntu.pkgs.org/22.04/ubuntu-main-amd64/tcpdump_4.99.1-3build2_amd64.deb.html
 # FIPS is still on Ubuntu 20.04 however, so don't create if using FIPS.
 
-sudo ln -s /usr/bin/tcpdump /usr/sbin/tcpdump
+if [ ! -e /usr/sbin/tcpdump ]; then
+	sudo ln -s /usr/bin/tcpdump /usr/sbin/tcpdump
+fi
 
 
 
@@ -168,13 +206,15 @@ sudo ln -s /usr/bin/tcpdump /usr/sbin/tcpdump
 # Send TCP keepalives every minute since GCE will terminate idle connections
 # after 10m. Note that keepalives still need to be requested by the application
 # with the SO_KEEPALIVE socket option.
-cat <<EOF > /etc/sysctl.d/99-roachprod-tcp-keepalive.conf
+if [ ! -e /etc/sysctl.d/99-roachprod-tcp-keepalive.conf ]; then
+	cat <<EOF > /etc/sysctl.d/99-roachprod-tcp-keepalive.conf
 net.ipv4.tcp_keepalive_time=60
 net.ipv4.tcp_keepalive_intvl=60
 net.ipv4.tcp_keepalive_probes=5
 EOF
 
-sysctl --system  # reload sysctl settings
+	sysctl --system  # reload sysctl settings
+fi
 
 
 
@@ -185,12 +225,14 @@ systemctl mask cron
 
 
 
-sudo apt-get install -qy chrony
+# If chrony is not already installed, install it.
+if ! dpkg -s chrony >/dev/null 2>&1; then
+	sudo apt-get install -qy chrony
 
-# Override the chrony config. In particular,
-# log aggressively when clock is adjusted (0.01s)
-# and exclusively use google's time servers.
-sudo cat <<EOF > /etc/chrony/chrony.conf
+	# Override the chrony config. In particular,
+	# log aggressively when clock is adjusted (0.01s)
+	# and exclusively use google's time servers.
+	sudo cat <<EOF > /etc/chrony/chrony.conf
 keyfile /etc/chrony/chrony.keys
 commandkey 1
 driftfile /var/lib/chrony/chrony.drift
@@ -206,8 +248,9 @@ server metadata.google.internal prefer iburst
 makestep 0.1 3
 EOF
 
-sudo /etc/init.d/chrony restart
-sudo chronyc -a waitsync 30 0.01 | sudo tee -a /root/chrony.log
+	sudo /etc/init.d/chrony restart
+	sudo chronyc -a waitsync 30 0.01 | sudo tee -a /root/chrony.log
+fi
 
 
 
@@ -226,26 +269,28 @@ done
 
 # Enable core dumps, do this last, something above resets /proc/sys/kernel/core_pattern
 # to just "core".
-cat <<EOF > /etc/security/limits.d/core_unlimited.conf
+if [ ! -e /bin/gzip_core.sh ]; then
+	cat <<EOF > /etc/security/limits.d/core_unlimited.conf
 * soft core unlimited
 * hard core unlimited
 root soft core unlimited
 root hard core unlimited
 EOF
 
-cat <<'EOF' > /bin/gzip_core.sh
+	cat <<'EOF' > /bin/gzip_core.sh
 #!/bin/sh
 exec /bin/gzip -f - > /mnt/data1/cores/core.$1.$2.$3.$4.gz
 EOF
-chmod +x /bin/gzip_core.sh
+	chmod +x /bin/gzip_core.sh
 
-CORE_PATTERN="|/bin/gzip_core.sh %e %p %h %t"
-echo "$CORE_PATTERN" > /proc/sys/kernel/core_pattern
-sed -i'~' 's/enabled=1/enabled=0/' /etc/default/apport
-sed -i'~' '/.*kernel\\.core_pattern.*/c\\' /etc/sysctl.conf
-echo "kernel.core_pattern=$CORE_PATTERN" >> /etc/sysctl.conf
+	CORE_PATTERN="|/bin/gzip_core.sh %e %p %h %t"
+	echo "$CORE_PATTERN" > /proc/sys/kernel/core_pattern
+	sed -i'~' 's/enabled=1/enabled=0/' /etc/default/apport
+	sed -i'~' '/.*kernel\\.core_pattern.*/c\\' /etc/sysctl.conf
+	echo "kernel.core_pattern=$CORE_PATTERN" >> /etc/sysctl.conf
 
-sysctl --system  # reload sysctl settings
+	sysctl --system  # reload sysctl settings
+fi
 
 
 
@@ -265,40 +310,60 @@ if systemctl is-active --quiet sshguard; then
 fi
 systemctl mask sshguard
 
+ssh_updated_config=0
 # increase the number of concurrent unauthenticated connections to the sshd
 # daemon. See https://en.wikibooks.org/wiki/OpenSSH/Cookbook/Load_Balancing.
 # By default, only 10 unauthenticated connections are permitted before sshd
 # starts randomly dropping connections.
-sudo sh -c 'echo "MaxStartups 64:30:128" >> /etc/ssh/sshd_config'
+if ! grep -q '^MaxStartups' /etc/ssh/sshd_config; then
+	sudo sh -c 'echo "MaxStartups 64:30:128" >> /etc/ssh/sshd_config'
+	ssh_updated_config=1
+fi
 
 # Crank up the logging for issues such as:
 # https://github.com/cockroachdb/cockroach/issues/36929
-sudo sed -i'' 's/LogLevel.*$/LogLevel DEBUG3/' /etc/ssh/sshd_config
+if ! grep -q '^LogLevel' /etc/ssh/sshd_config; then
+	sudo sed -i'' 's/LogLevel.*$/LogLevel DEBUG3/' /etc/ssh/sshd_config
+	ssh_updated_config=1
+fi
 
 # FIPS is still on Ubuntu 20.04 however, so don't enable if using FIPS.
 
-sudo sh -c 'echo "PubkeyAcceptedAlgorithms +ssh-rsa" >> /etc/ssh/sshd_config'
+if ! grep -q '^PubkeyAcceptedAlgorithms' /etc/ssh/sshd_config; then
+	sudo sh -c 'echo "PubkeyAcceptedAlgorithms +ssh-rsa" >> /etc/ssh/sshd_config'
+	ssh_updated_config=1
+fi
 
 
-sudo sed -i 's/#LoginGraceTime .*/LoginGraceTime 0/g' /etc/ssh/sshd_config
-sudo sed -i 's/TCPKeepAlive no/TCPKeepAlive yes/g' /etc/ssh/sshd_config
+if ! grep -q '^LoginGraceTime' /etc/ssh/sshd_config; then
+	sudo sed -i 's/#LoginGraceTime .*/LoginGraceTime 0/g' /etc/ssh/sshd_config
+	ssh_updated_config=1
+fi
+if ! grep -q '^TCPKeepAlive' /etc/ssh/sshd_config; then
+	sudo sed -i 's/TCPKeepAlive no/TCPKeepAlive yes/g' /etc/ssh/sshd_config
+	ssh_updated_config=1
+fi
 
-sudo service sshd restart
-sudo service ssh restart
+if [ "$ssh_updated_config" -eq 1 ]; then
+	echo "Restarting sshd to apply updated configuration"
+	sudo service sshd restart
+	sudo service ssh restart
+fi
 
 
 
-# Add and start node_exporter, only authorize scrapping from internal network.
-export ARCH=$(dpkg --print-architecture)
+# If node_exporter is not already installed, install it.
 export DEFAULT_USER_HOME="/home/$(id -nu 1000)"
-mkdir -p ${DEFAULT_USER_HOME}/node_exporter && curl -fsSL \
-	https://storage.googleapis.com/cockroach-test-artifacts/prometheus/node_exporter-1.2.2.linux-${ARCH}.tar.gz |
-	tar zxv --strip-components 1 -C ${DEFAULT_USER_HOME}/node_exporter \
-	&& chown -R 1000:1000 ${DEFAULT_USER_HOME}/node_exporter
+if [ ! -e "${DEFAULT_USER_HOME}/node_exporter/node_exporter" ]; then
+	export ARCH=$(dpkg --print-architecture)
+	mkdir -p ${DEFAULT_USER_HOME}/node_exporter && curl -fsSL \
+		https://storage.googleapis.com/cockroach-test-artifacts/prometheus/node_exporter-1.2.2.linux-${ARCH}.tar.gz |
+		tar zxv --strip-components 1 -C ${DEFAULT_USER_HOME}/node_exporter \
+		&& chown -R 1000:1000 ${DEFAULT_USER_HOME}/node_exporter
+fi
 
-export SCRAPING_PUBLIC_IPS=$(dig +short prometheus.testeng.crdb.io | awk '{printf "%s%s",sep,$0; sep=","} END {print ""}')
-sudo iptables -A INPUT -s 127.0.0.1,10.0.0.0/8,${SCRAPING_PUBLIC_IPS} -p tcp --dport 9100 -j ACCEPT
-sudo iptables -A INPUT -p tcp --dport 9100 -j DROP
+
+export DEFAULT_USER_HOME="/home/$(id -nu 1000)"
 (
 	cd ${DEFAULT_USER_HOME}/node_exporter && \
 	sudo systemd-run --unit node_exporter --same-dir \
@@ -307,19 +372,25 @@ sudo iptables -A INPUT -p tcp --dport 9100 -j DROP
 		--web.telemetry-path="/metrics"
 )
 
-
-
-# Add and start ebpf_exporter, only authorize scrapping from internal network.
-export ARCH=$(dpkg --print-architecture)
-export DEFAULT_USER_HOME="/home/$(id -nu 1000)"
-mkdir -p ${DEFAULT_USER_HOME}/ebpf_exporter && curl -fsSL \
-	https://storage.googleapis.com/cockroach-test-artifacts/prometheus/ebpf_exporter-2.4.2.linux-${ARCH}.tar.gz |
-	tar zxv --strip-components 1 -C ${DEFAULT_USER_HOME}/ebpf_exporter \
-	&& chown -R 1000:1000 ${DEFAULT_USER_HOME}/ebpf_exporter
-
 export SCRAPING_PUBLIC_IPS=$(dig +short prometheus.testeng.crdb.io | awk '{printf "%s%s",sep,$0; sep=","} END {print ""}')
-sudo iptables -A INPUT -s 127.0.0.1,10.0.0.0/8,${SCRAPING_PUBLIC_IPS} -p tcp --dport 9435 -j ACCEPT
-sudo iptables -A INPUT -p tcp --dport 9435 -j DROP
+sudo iptables -A INPUT -s 127.0.0.1,10.0.0.0/8,${SCRAPING_PUBLIC_IPS} -p tcp --dport 9100 -j ACCEPT
+sudo iptables -A INPUT -p tcp --dport 9100 -j DROP
+
+
+
+
+# If ebpf_exporter is not already installed, install it.
+export DEFAULT_USER_HOME="/home/$(id -nu 1000)"
+if [ ! -e "${DEFAULT_USER_HOME}/ebpf_exporter/ebpf_exporter" ]; then
+	export ARCH=$(dpkg --print-architecture)
+	mkdir -p ${DEFAULT_USER_HOME}/ebpf_exporter && curl -fsSL \
+		https://storage.googleapis.com/cockroach-test-artifacts/prometheus/ebpf_exporter-2.4.2.linux-${ARCH}.tar.gz |
+		tar zxv --strip-components 1 -C ${DEFAULT_USER_HOME}/ebpf_exporter \
+		&& chown -R 1000:1000 ${DEFAULT_USER_HOME}/ebpf_exporter
+fi
+
+
+export DEFAULT_USER_HOME="/home/$(id -nu 1000)"
 (
 	cd ${DEFAULT_USER_HOME}/ebpf_exporter && \
 	sudo systemd-run --unit ebpf_exporter --same-dir \
@@ -330,7 +401,27 @@ sudo iptables -A INPUT -p tcp --dport 9435 -j DROP
 		--web.telemetry-path="/metrics"
 )
 
+export SCRAPING_PUBLIC_IPS=$(dig +short prometheus.testeng.crdb.io | awk '{printf "%s%s",sep,$0; sep=","} END {print ""}')
+sudo iptables -A INPUT -s 127.0.0.1,10.0.0.0/8,${SCRAPING_PUBLIC_IPS} -p tcp --dport 9435 -j ACCEPT
+sudo iptables -A INPUT -p tcp --dport 9435 -j DROP
 
+
+
+
+# Touch the disks initialized file to mark that initialization is complete.
 sudo touch /.roachprod-initialized
+
+
+
+
+# Log the ending time of the script with a timestamp
+echo "startup script ending: $(date -u)"
+
+
+
+# Log the ending time of the script with a timestamp
+echo "startup script ending: $(date -u)"
+
+
 ----
 ----
