lint: githooks to check for documentation
Fixes #64909

The purpose of this linter is to provide information to the Docs team about why a commit was made. This can be a reference to an epic, a reference to an issue or via free-form text describing why the change was necessary. The Docs team will use this information to determine if the change requires changes to any documentation.

For more information about commit documentation please refer to:
https://cockroachlabs.atlassian.net/wiki/spaces/devinf/pages/2009039063/DRAFT+Jira+Epic+Ref+GitHub+Issue+Ref+Docs+Note

Release note: None

diff --git a/githooks/commit-msg b/githooks/commit-msg
--- a/githooks/commit-msg
+++ b/githooks/commit-msg
@@ -175,3 +175,48 @@ else
     done
     if test -n "$informed"; then echo >&2; fi
 fi
+
+# Lint for the existence of an issue reference, an epic reference or a Docs section
+# describing why the change is being made.
+# TODO: add the correct link for documentation
+# https://cockroachlabs.atlassian.net/wiki/spaces/devinf/pages/2009039063/DRAFT+Jira+Epic+Ref+GitHub+Issue+Ref+Docs+Note
+
+# The more complex regexes below have external test suites. At a future point we may
+# add tests for these that run in CI. In the meantime, please refer to the below links:
+# - isdocs: https://regexr.com/611mp
+# - isepic: https://regexr.com/611qq
+# - iskeyphrase1: https://regexr.com/611nb
+# - iskeyphrase2: https://regexr.com/611r0
+# - isissue1: https://regexr.com/611rr
+# - isissue2: https://regexr.com/611ss
+
+ISSUE="[Cc]lose [Cc]loses [Cc]losed [Ff]ix [Ff]ixes [Ff]ixed [Rr]esolve [Rr]esolves [Rr]esolved"
+
+isdocs=`$grep -cE '^[Dd]ocs note:\s' "$1"`
+isepic=`$grep -cE "^[Ee]pic:?\s+[A-Z][A-Z]+-[0-9][0-9]*(\s.*)?$" "$1"`
+iskeyphrase1=`$grep -cE "^([Ss]ee also|[Ii]nforms):?\s+#[0-9][0-9]*([,\s].*)?$" "$1"`
+iskeyphrase2=`$grep -cE "^([Ss]ee also|[Ii]nforms):\s+[A-Za-z0-9_.-]*[/][A-Za-z0-9_.-]*#[0-9][0-9]*([,\s].*)?$" "$1"`
+
+if [[ $(($isdocs + $isepic + $iskeyphrase1 + $iskeyphrase2)) -eq 0 ]]; then
+    FAILED="yes"
+    for status in $ISSUE; do
+        isissue1=$($grep -cE "^($status):?\s+#[0-9][0-9]*([\s,].*)?$" "$1")
+        # Only check for valid github usernames, repo and org name characters
+        # https://stackoverflow.com/questions/59081778/rules-for-special-characters-in-github-repository-name
+        isissue2=$($grep -cE "^($status):?\s+[A-Za-z0-9_.-]*[/][A-Za-z0-9_.-]*#[0-9][0-9]*([\s,].*)?$" "$1")
+        if [[ $isissue1 -ne 0 || $isissue2 -ne 0 ]]; then
+            FAILED="no"
+            break
+        fi
+    done
+    if [ "$FAILED" == "yes" ]; then
+        warn "Missing one of: issue reference, epic reference or Docs:_ section"
+        echo "Try one of these:" >&2
+        echo >&2
+        echo "  fixes #12345" >&2
+        echo "  epic CRDB-12345" >&2
+        echo "  See also: #62585" >&2
+        echo "  Docs note: This change is being made because ..." >&2
+        echo >&2
+    fi
+fi
